// <auto-generated />
namespace OPSA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class what : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(what));
        
        string IMigrationMetadata.Id
        {
            get { return "201805012034326_what"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
